Upgrade scicloj ml deps
scicloj/noj pull request #66
Opened 2024-11-28 22:06 UTC by behrica

2024-11-29 16:48 UTC, daslu commented
Nice, I'll look a little later.

2024-11-29 21:56 UTC, behrica commented
I added an auto generated list of all direct libs with version and licence.

2024-11-29 22:18 UTC, daslu requested changes
@behrica that looks great.

My only comment is that Hanamicloth was replaced by Tableplot so it is not needed.

2024-11-29 22:18 UTC, daslu commented on deps.edn
> +        org.scicloj/hanamicloth                   {:mvn/version "1-alpha8"}
This was replaced by Tableplot

2024-11-30 14:13 UTC, behrica commented on deps.edn
> +        org.scicloj/hanamicloth                   {:mvn/version "1-alpha8"}
solved and rebased

2024-11-30 15:09 UTC, daslu commented
Great, merging

2024-11-30 15:09 UTC, merged